# Redis Semantic Cache :- This stores answers generated by the LLM using embedding hash of query :)


import redis
import hashlib
import json
import numpy as np


class RedisCache:

    def __init__(self, host="localhost", port=6379, ttl=3600): # ttl is time to live for cache entries, default is 1 hour

        self.ttl = ttl

        self.client = redis.Redis(
            host=host,
            port=port,
            decode_responses=True
        )

        print("Connected to Redis cache") # this will print a message when the connection to Redis cache is established

# HASHING - here we will create a stable hash from the embedding vector of the query using SHA-256 algorithm, which will be used as the key in Redis cache to store and retrieve the cached answers.

    def _hash_vector(self, vec: np.ndarray) -> str: # this will return a string hash for the given vector
        """
        Create stable hash from embedding
        """
        vec_bytes = vec.tobytes()
        return hashlib.sha256(vec_bytes).hexdigest() # this will return a unique hash for the given vector, which will be used as the key in Redis cache

# GET - here we will retrieve the cached answer from Redis cache using the hash of the query vector as the key, and if the cache entry exists, we will return the cached answer after converting it back from JSON string to Python object, otherwise we will return None to indicate a cache miss.

    def get(self, query_vec): # this will return the cached answer for the given query vector if it exists, otherwise None

        key = self._hash_vector(query_vec)

        val = self.client.get(key)

        if val:
            print("Cache HIT")
            return json.loads(val) # VVIP this will convert the JSON string back to a Python object before returning

        print("Cache MISS")
        return None

# SET - here we will store the answer in the Redis cache with the key as the hash of the query vector and the value as the JSON string of the answer, and we will set an expiration time for the cache entry using ttl (time to live) parameter.

    def set(self, query_vec, answer): # this will cache the answer for the given query vector

        key = self._hash_vector(query_vec)

        self.client.setex(
            key,
            self.ttl,
            json.dumps(answer) # this will convert the answer to a JSON string before storing in Redis cache
        )

# THANKYOU JI FOR REVIEWING MY CODE HOPING TO CONNECT WITH U FOR THE NEXT ROUND OF INTERVIEW :) SHAKTESH